services:
  django:
    build:
      context: .
      dockerfile: ./Django_Dockerfile
    restart: always
    command: python sumsaar/webserver/manage.py runserver 0.0.0.0:8000
    container_name: sumsaar_django
    volumes:
    - ../:/app
    ports:
    - "8010:8000"
    depends_on:
      - django-migrate
      - playwright
    environment:
      PLAYWRIGHT_WS_ENDPOINT: ws://playwright:3000?ws=1

  django-migrate:
    build:
      context: .
      dockerfile: ./Django_Dockerfile
    command: >
      sh -c "python sumsaar/webserver/manage.py makemigrations &&
             python sumsaar/webserver/manage.py migrate"
    volumes:
    - ../:/app
    depends_on:
      postgres:
        condition: service_healthy

  celery-worker:
    build:
      context: .
      dockerfile: ./Celery_Dockerfile
    command: celery -A webserver worker -l info
    volumes:
      - ../:/app
    depends_on:
      - django
      - redis
      - playwright
    environment:
      PLAYWRIGHT_WS_ENDPOINT: ws://playwright:3000?ws=1
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]


  postgres:
    image: pgvector/pgvector:pg18
    environment:
      POSTGRES_USER: nayak
      POSTGRES_PASSWORD: testing@123
      POSTGRES_DB: sumsaar
    volumes:
      - postgres-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "nayak", "-d", "sumsaar"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always

  redis:
    image: redis:7.2-bookworm
    ports:
      - '6378:6379'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 50
      start_period: 30s
    restart: always

  playwright:
    image: mcr.microsoft.com/playwright:v1.58.0-jammy
    command: npx -y playwright run-server --port 3000 --host 0.0.0.0
    ipc: host
    ports:
      - "3000:3000"
    restart: always

volumes:
  postgres-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./postgres-data
